#server:
#  port: 8014
#
#
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  datasource:
#    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: weida
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: service-yiqing
#  profiles:
#    active: dev
#
#mybatis-plus:
#  mapper-locations: classpath:generator/*.xml
##mybatis日志
#  configuration:
#        log:
#          impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
##返回json的全局时间格式
#  spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#  spring.jackson.time-zone=GMT+8
